extends: [default]

rules:
  npm:
    enabled: false
  pnpm:
    include: ['package.json']
    exclude: ['**/node_modules/**', '**/dist/**', '**/.tests_playwright/**']
    groups:
      vue:
        - vue
        - vuex
      webpack:
        - webpack
        - webpack-cli
        - webpack-dev-server
      babel:
        - babel-loader
        - '@babel/core'
        - '@babel/preset-env'
      playwright:
        - playwright
        - '@playwright/test'
    package_overrides:
      # @vue/devtools-api pinned to v6 — v7+ dropped API that vuex 4.x depends on
      # No CVEs. Fix: migrate Vuex→Pinia (significant effort). No EOL date set.
      # Risk: LOW — dev-only dependency, not shipped to production, no security exposure.
      '@vue/devtools-api':
        outdated:
          exclude_version_patterns: ["^[789]\\.", "^\\d{2,}\\."]
      # eslint pinned to v9 — v10 requires .eslintrc.js→eslint.config.js rewrite
      # No CVEs. Fix: ~1-2h flat config migration. EOL: August 2026.
      # Risk: LOW — dev-only tooling, no runtime/production impact. Migrate before EOL
      #   to keep receiving security patches, but missing the deadline is not critical.
      eslint:
        outdated:
          exclude_version_patterns: ["^\\d{2,}\\."]
      eslint-plugin-vue:
        outdated:
          exclude_version_patterns: ["^\\d{2,}\\."]
  yarn:
    enabled: false
  composer:
    enabled: false
  requirements:
    enabled: false
  pipfile:
    enabled: false
  mod:
    enabled: false
  msbuild:
    enabled: false
  nuget:
    enabled: false

system_tests:
  run_preflight: false
  run_mode: after_all
  stop_on_fail: false
  tests:
    - name: build
      commands: |
        pnpm install
        pnpm run build
      timeout_seconds: 300
    - name: e2e-tests
      commands: ./e2e.sh
      timeout_seconds: 900
