extends: [default]

rules:
  npm:
    enabled: false
  pnpm:
    include: ['**/package.json']
    exclude: ['**/node_modules/**', '**/dist/**', '**/.tests_playwright/**']
    groups:
      vue:
        - vue
        - vuex
      react:
        - react
        - react-dom
      webpack:
        - webpack
        - webpack-cli
        - webpack-dev-server
      babel:
        - babel-loader
        - '@babel/core'
        - '@babel/preset-env'
      playwright:
        - playwright
        - '@playwright/test'
  yarn:
    enabled: false
  composer:
    enabled: false
  requirements:
    enabled: false
  pipfile:
    enabled: false
  mod:
    enabled: false
  msbuild:
    enabled: false
  nuget:
    enabled: false

system_tests:
  run_preflight: false
  run_mode: after_all
  stop_on_fail: false
  tests:
    - name: build
      commands: |
        pnpm install
        pnpm run build
      timeout_seconds: 300
    - name: e2e-tests
      commands: ./e2e.sh
      timeout_seconds: 900
