# Frontend App - goupdate configuration
# Example: pnpm-based Vue.js frontend with grouped dependencies
#
# Based on matematikk-mooc/frontend project structure

extends: [default]

rules:
  pnpm:
    # Only group packages with actual version coupling (peer dependencies)
    groups:
      # Vue core - vuex/vue-router have peer deps on vue
      vue:
        - vue
        - vuex
        - vue-router

      # React - must have matching versions
      react:
        - react
        - react-dom

      # Webpack core - cli/dev-server depend on webpack
      webpack:
        - webpack
        - webpack-cli
        - webpack-dev-server

      # Babel - loader depends on core
      babel:
        - babel-loader
        - "@babel/core"
        - "@babel/preset-env"

      # Playwright - test package depends on playwright
      playwright:
        - playwright
        - "@playwright/test"

    # Note: Pre-release filtering inherits from default config
    # Default patterns exclude: alpha, beta, rc, dev, canary, snapshot, nightly, preview, next

# System test to verify no compile errors after updates
system_tests:
  run_preflight: true
  run_mode: after_each
  stop_on_fail: true
  tests:
    - name: build
      commands: |
        pnpm install
        pnpm run build
      timeout_seconds: 300
