require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git
task :with_capose do
    require "capose"
  end
  task "staging" => [:with_capose]