name: Branch - PR

on:
  pull_request:
    branches:
      - stage
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: Utdanningsdirektoratet/dit-github-actions/github/runtimes@v1
        with:
          node-version: '22'
          node-pms: pnpm
      - uses: Utdanningsdirektoratet/dit-github-actions/js/install@v1
      - name: Build
        run: pnpm run production
